 pipeline {
	agent any

	tools {
		maven 'maven'
		jdk 'java19'
	}

	stages {
		stage("delete workspace before build starts") {
			steps {
				echo 'Deleting workspace'
				deleteDir()
			}
		}

		stage("build") {
			steps {
				 sh 'mvn pom.xml clean'
			}
			
		}
		
		stage("test") {
			steps {
				 sh 'mvn -f pom.xml install'
			}
		}
		
		stage("build docker image") {
			steps {
				script {
					sh 'docker build -t pseudo_scene .'
				}
			}
		}
	}
	
	post {
		failure {
		  // notify users when the Pipeline fails
			mail to: 'dhfingerstyle@gmail.com',
			subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
			body: "Something is wrong with ${env.BUILD_URL}"
		}
	}
	   
}
