 pipeline {
	agent any

	tools {
		maven 'maven'
		jdk 'java19'
	}

	stages {
		stage("build") {
			steps {
				 sh 'mvn -f pseudo_scene/pom.xml clean'
			}
			
		}
		
		stage("test") {
			steps {
				 sh 'mvn -f pseudo_scene/pom.xml install'
			}
		}
	}
	
	post {
		failure {
		  // notify users when the Pipeline fails
			mail to: 'dhfingerstyle@gmail.com',
			subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
			body: "Something is wrong with ${env.BUILD_URL}"
		}
	}
	   
}
